// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy-B17TRdB5kvXakaxHAM0rNBgY32oJW4',
    appId: '1:832012029846:web:39aba589da11a1364fd7b7',
    messagingSenderId: '832012029846',
    projectId: 'cekongkir-3b3a0',
    authDomain: 'cekongkir-3b3a0.firebaseapp.com',
    storageBucket: 'cekongkir-3b3a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqin-hz63l0SO_t_mAsjKRhFnDVIgHiAE',
    appId: '1:832012029846:android:6526d1ddc6f2d9da4fd7b7',
    messagingSenderId: '832012029846',
    projectId: 'cekongkir-3b3a0',
    storageBucket: 'cekongkir-3b3a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_HwFlVyXOS_lqhbVipefntB1jtLzQKJ4',
    appId: '1:832012029846:ios:d9e859967bf8d3e94fd7b7',
    messagingSenderId: '832012029846',
    projectId: 'cekongkir-3b3a0',
    storageBucket: 'cekongkir-3b3a0.appspot.com',
    iosBundleId: 'com.example.cekOngkir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_HwFlVyXOS_lqhbVipefntB1jtLzQKJ4',
    appId: '1:832012029846:ios:d50141f2f0b252a14fd7b7',
    messagingSenderId: '832012029846',
    projectId: 'cekongkir-3b3a0',
    storageBucket: 'cekongkir-3b3a0.appspot.com',
    iosBundleId: 'com.example.cekOngkir.RunnerTests',
  );
}
